db:
  sqlite:
    db-path: /var/lib/dunsumday/db.sqlite
    schema-path: /usr/local/share/dunsumday/lib/db-schema
webserver:
  paths:
    ui: /usr/share/dunsumday/webserver/resources/ui
  server:
    all-interfaces: true
    port: 26300
    root-path: /
    paths:
      api: /api
      ui: /ui
